# ============================================================
# OFFICE CONFIG   Generated by Setup Wizard
# This is the ONLY file that needs to change when deploying
# to a new office. All scripts import from here.
# ============================================================

OFFICE = {
    "name":     "Pristine Dental Center",
    "timezone": "America/New_York",
}

# Password required to open the office dashboard at port 5000.
# To change it later, run reconfigure.bat.
DASHBOARD_PASSWORD = "281194"

DB_CONFIG = {
    "host":     "server",
    "port":     3306,
    "database": "opendental",
    "user":     "root",
    "password": "19082",
}

GMAIL_CONFIG = {
    "sender_email":    "pristine9027@gmail.com",
    "sender_password": "nhxx bubh wksh naga",
}

# =============================================================================
# RECIPIENTS
# =============================================================================

PROVIDER_EMAILS = {
    "Dhaval Shah": "pristine392@gmail.com",
    "Zainab Al-Azzawi": "pristine392@gmail.com",
    "Ankita Lulla": "pristine392@gmail.com",
    "Nesreen Ibrahim": "",
    "Shubhsangeet Johal": "pristine392@gmail.com",
    "Maha Tayefeh": "",
    "Taksh Shah": "pristine392@gmail.com",
}

MANAGER_EMAIL    = "pristine9027@gmail.com"
FRONT_DESK_EMAIL = "pristine392@gmail.com"

# =============================================================================
# FOLDERS
# =============================================================================

FOLDERS = {
    "base":           r"C:\dental_automation",
    "unsigned_notes": r"C:\dental_automation\unsigned_notes",
    "provider_notes": r"C:\dental_automation\unsigned_notes\provider_notes",
    "huddle":         r"C:\dental_automation\huddle_summary",
    "recall":         r"C:\dental_automation\recall_list",
    "production":     r"C:\dental_automation\production",
}

# =============================================================================
# SCHEDULES
# =============================================================================

SCHEDULES = {
    "unsigned_notes": "10:00 AM daily",
    "huddle_summary": "08:00 AM daily",
    "recall_list":    "08:00 AM Monday",
    "production":     "07:00 PM daily",
}

# =============================================================================
# UNSIGNED NOTES SETTINGS
# =============================================================================

UNSIGNED_NOTES_SETTINGS = {
    "lookback_days":        30,
    "perio_lookahead_days": 30,
    "notes_retention_days": 7,
}

# =============================================================================
# INSURANCE VERIFICATION SETTINGS
# =============================================================================

INS_VERIFY_SETTINGS = {
    "green_days":  7,
    "yellow_days": 15,
}

# =============================================================================
# RECALL SETTINGS
# =============================================================================

RECALL_SETTINGS = {
    "interval_months":       6,
    "grace_period_months":   1,
    "lookback_appointments": 5,
    "low_priority_carriers": [
        "keystone first",
        "keystone first dentaquest",
        "keystone first vip",
        "keystone mercy",
        "upmc",
        "united healthcare community plan",
        "health partners",
        "health partner",
        "health partner medicare",
        "aetna better health",
        "dentaquest",
        "avesis",
    ],
}

# =============================================================================
# PRODUCTION DASHBOARD SETTINGS
# =============================================================================

PAYMENT_TYPES = {
    69:  "Check",
    70:  "Cash",
    71:  "Credit Card",
    72:  "Patient Refund",
    313: "Cash",
    314: "Check",
    316: "Credit Card",
    317: "Online BillPay",
    318: "EFT",
    364: "Care Credit",
    397: "Modento",
    406: "Proceed Finance",
    412: "Cherry Payments",
    414: "Message-to-Pay",
    415: "FHD",
    315: "Insurance Check",
}

PAYMENT_GROUPS = {
    "Cash":          [70, 313],
    "Check":         [69, 314],
    "Credit Card":   [71, 316, 364, 397, 406, 412, 414, 415],
    "EFT / Online":  [317, 318],
    "Insurance Check": [315],
    "Patient Refund": [72],
}

PRODUCTION_SETTINGS = {
    "insurance_payment_note": True,
}

# =============================================================================
# MEDICAID CARRIERS
# =============================================================================

MEDICAID_CARRIERS_BASE = [
        "keystone first",
        "keystone first dentaquest",
        "keystone first vip",
        "keystone mercy",
        "upmc",
        "united healthcare community plan",
        "health partners",
        "health partner",
        "health partner medicare",
        "aetna better health",
        "dentaquest",
        "avesis",
]

MEDICAID_CARRIERS_EXTRA = []

MEDICAID_CARRIERS = MEDICAID_CARRIERS_BASE + MEDICAID_CARRIERS_EXTRA

# =============================================================================
# AR DASHBOARD SETTINGS
# =============================================================================

AR_SETTINGS = {
    "sheet_id":       "1WJecMp3LX9sncgzeJx1Q4z2Ndi4Ts7uHA8448wyngAs",
    "credentials":    r"C:\dental_automation\ar\credentials.json",
    "dashboard_port": 5002,
}
